# Site configuration — single source of truth for all 7 sites
# Change values here, run py shared/build.py, deploy → all pages update

SITES = {
    "main-site": {
        "domain": "www.jycsd.com",
        "base_url": "https://www.jycsd.com",
        "brand_name": "Myers Media",
        "brand_slogan": "Your Guide to Better Living",
        "brand_desc": "Your gateway to expert lifestyle guides across multiple domains.",
        "brand_logo_text": "Myers",
        "brand_logo_accent": "Media",
        "colors": {
            "primary": {50: '#eff6ff', 100: '#dbeafe', 200: '#bfdbfe', 400: '#60a5fa', 500: '#3b82f6', 600: '#2563eb', 700: '#1d4ed8', 800: '#1e40af', 900: '#1e3a8a'},
            "navy": '#0f1a3c',
            "slate": '#334155',
        },
        "font_sans": ['Roboto', 'Arial', 'Helvetica', 'sans-serif'],
        "font_heading": ['Georgia', 'Times New Roman', 'serif'],
        "accent_text": "text-primary-600",
        "accent_hover": "hover:text-primary-600",
        "body_class": "bg-white text-gray-800 font-sans",
        "nav_bg": "bg-white/95 backdrop-blur border-b border-gray-100",
        "nav_items": [
            {"label": "Home", "href": "index.html"},
            {"label": "Our Sites", "href": "#sites"},
            {"label": "About", "href": "about.html"},
            {"label": "Contact", "href": "contact.html"},
        ],
        "footer_brand": "Myers Media",
        "footer_accent_color": "primary-400",
        "hero_gradient": "from-navy via-primary-900 to-primary-800",
        "stat_bar_bg": "bg-primary-50 border-b border-primary-100",
        "article_card_class": "site-card",
        "button_primary": "bg-primary-700 hover:bg-primary-800",
        "link_color": "text-primary-600",
        "subsites": ["healthy", "pets", "home", "finance", "tech", "travel"],
        "extra_styles": "site-card",
    },
    "sub-healthy": {
        "domain": "healthy.jycsd.com",
        "base_url": "https://healthy.jycsd.com",
        "brand_name": "HealthyEats",
        "brand_slogan": "Eat Better, Live Better",
        "brand_desc": "Evidence-based nutrition guides, healthy recipes, and meal plans.",
        "brand_logo_text": "Healthy",
        "brand_logo_accent": "Eats",
        "build_name": "HealthyEats",
        "colors": {
            "brand": {50: '#f0fdf4', 100: '#dcfce7', 200: '#bbf7d0', 400: '#4ade80', 500: '#22c55e', 600: '#16a34a', 700: '#15803d', 800: '#166534'},
        },
        "font_sans": ['Inter', 'system-ui', '-apple-system', 'sans-serif'],
        "font_heading": ['Georgia', 'Times New Roman', 'serif'],
        "accent_text": "text-brand-600",
        "accent_hover": "hover:text-brand-600",
        "body_class": "bg-gray-50 text-gray-800",
        "nav_bg": "bg-white shadow-sm sticky top-0 z-50",
        "nav_items": [
            {"label": "Home", "href": "index.html"},
            {"label": "Recipes", "href": "category-recipes.html"},
            {"label": "Nutrition", "href": "category-nutrition.html"},
            {"label": "Meal Plans", "href": "category-meal-plans.html"},
            {"label": "About", "href": "about.html"},
            {"label": "Contact", "href": "contact.html"},
        ],
        "footer_brand": "HealthyEats",
        "footer_accent_color": "brand-500",
        "hero_gradient": "from-brand-50 to-green-100",
        "article_card_class": "article-card",
        "button_primary": "bg-brand-600 hover:bg-brand-700",
        "link_color": "text-brand-600",
        "extra_styles": "ad-style",
    },
    "sub-pets": {
        "domain": "pets.jycsd.com",
        "base_url": "https://pets.jycsd.com",
        "brand_name": "PetCare Hub",
        "brand_slogan": "Expert Pet Care Made Simple",
        "brand_desc": "Expert pet care advice for happy, healthy companions.",
        "brand_logo_text": "PetCare ",
        "brand_logo_accent": "Hub",
        "build_name": "PetCare Hub",
        "colors": {
            "brand": {50: '#fff7ed', 100: '#ffedd5', 200: '#fed7aa', 400: '#fb923c', 500: '#f97316', 600: '#ea580c', 700: '#c2410c', 800: '#9a3412'},
            "dark": '#1c1917',
        },
        "font_sans": ['Roboto', 'Arial', 'Helvetica', 'sans-serif'],
        "accent_text": "text-brand-600",
        "accent_hover": "hover:text-brand-600",
        "body_class": "bg-stone-50 text-gray-800 font-sans",
        "nav_bg": "bg-white shadow-sm sticky top-0 z-50",
        "nav_items": [
            {"label": "Home", "href": "index.html"},
            {"label": "Dogs", "href": "category-dogs.html"},
            {"label": "Cats", "href": "category-cats.html"},
            {"label": "Small Pets", "href": "category-small-pets.html"},
            {"label": "About", "href": "about.html"},
            {"label": "Contact", "href": "contact.html"},
        ],
        "footer_brand": "PetCare Hub",
        "footer_accent_color": "brand-500",
        "hero_gradient": "from-brand-50 to-orange-100",
        "article_card_class": "article-card",
        "button_primary": "bg-brand-500 hover:bg-brand-600",
        "link_color": "text-brand-600",
        "extra_styles": "ad-style",
    },
    "sub-home": {
        "domain": "home.jycsd.com",
        "base_url": "https://home.jycsd.com",
        "brand_name": "HomeJoy",
        "brand_slogan": "Your Home, Elevated",
        "brand_desc": "DIY home improvement, indoor gardening, and seasonal maintenance guides.",
        "brand_logo_text": "Home",
        "brand_logo_accent": "Joy",
        "build_name": "HomeJoy",
        "colors": {
            "lime": {50: '#f7fee7', 100: '#ecfccb', 200: '#d9f99d', 400: '#a3e635', 500: '#84cc16', 600: '#65a30d', 700: '#4d7c0f'},
            "stone": {50: '#fafaf9', 100: '#f5f5f4', 600: '#57534e', 800: '#292524'},
        },
        "font_sans": ['Roboto', 'Arial', 'Helvetica', 'sans-serif'],
        "accent_text": "text-lime-600",
        "accent_hover": "hover:text-lime-600",
        "body_class": "bg-stone-50 text-stone-800 font-sans",
        "nav_bg": "bg-white shadow-sm sticky top-0 z-50",
        "nav_items": [
            {"label": "Home", "href": "index.html"},
            {"label": "DIY", "href": "article-1.html"},
            {"label": "Gardening", "href": "article-2.html"},
            {"label": "Decor", "href": "article-3.html"},
            {"label": "About", "href": "about.html"},
            {"label": "Contact", "href": "contact.html"},
        ],
        "footer_brand": "HomeJoy",
        "footer_accent_color": "lime-500",
        "hero_gradient": "from-lime-50 to-green-100",
        "article_card_class": "",
        "button_primary": "bg-lime-600 hover:bg-lime-700",
        "link_color": "text-lime-600",
        "extra_styles": "",
    },
    "sub-finance": {
        "domain": "finance.jycsd.com",
        "base_url": "https://finance.jycsd.com",
        "brand_name": "MoneyWise",
        "brand_slogan": "Smart Money, Simple Life",
        "brand_desc": "Personal finance made simple — investing, budgeting, credit tips, and retirement planning.",
        "brand_logo_text": "Money",
        "brand_logo_accent": "Wise",
        "build_name": "MoneyWise",
        "colors": {
            "brand": {50: '#eff6ff', 100: '#dbeafe', 200: '#bfdbfe', 400: '#60a5fa', 500: '#3b82f6', 600: '#2563eb', 700: '#1d4ed8', 800: '#1e40af'},
        },
        "font_sans": ['Roboto', 'Arial', 'Helvetica', 'sans-serif'],
        "accent_text": "text-brand-600",
        "accent_hover": "hover:text-brand-600",
        "body_class": "bg-gray-50 text-gray-800 font-sans",
        "nav_bg": "bg-white shadow-sm sticky top-0 z-50",
        "nav_items": [
            {"label": "Home", "href": "index.html"},
            {"label": "Investing", "href": "article-1.html"},
            {"label": "Budgeting", "href": "article-2.html"},
            {"label": "Credit", "href": "article-3.html"},
            {"label": "Retirement", "href": "article-4.html"},
            {"label": "About", "href": "about.html"},
            {"label": "Contact", "href": "contact.html"},
        ],
        "footer_brand": "MoneyWise",
        "footer_accent_color": "brand-500",
        "hero_gradient": "from-brand-50 to-blue-100",
        "article_card_class": "article-card",
        "button_primary": "bg-brand-600 hover:bg-brand-700",
        "link_color": "text-brand-600",
        "extra_styles": "ad-style",
    },
    "sub-tech": {
        "domain": "tech.jycsd.com",
        "base_url": "https://tech.jycsd.com",
        "brand_name": "TechNest",
        "brand_slogan": "Tech Made Clear",
        "brand_desc": "Honest tech reviews, buying guides, productivity tools, and cybersecurity tips.",
        "brand_logo_text": "Tech",
        "brand_logo_accent": "Nest",
        "build_name": "TechNest",
        "colors": {
            "brand": {50: '#f8fafc', 100: '#f1f5f9', 200: '#e2e8f0', 400: '#94a3b8', 500: '#64748b', 600: '#475569', 700: '#334155', 800: '#1e293b'},
        },
        "font_sans": ['Roboto', 'system-ui', '-apple-system', 'sans-serif'],
        "font_heading": ['Roboto', 'Arial', 'sans-serif'],
        "accent_text": "text-brand-600",
        "accent_hover": "hover:text-brand-600",
        "body_class": "bg-gray-50 text-gray-800 font-sans",
        "nav_bg": "bg-white shadow-sm sticky top-0 z-50",
        "nav_items": [
            {"label": "Home", "href": "index.html"},
            {"label": "Reviews", "href": "category-reviews.html"},
            {"label": "Guides", "href": "category-guides.html"},
            {"label": "AI", "href": "category-ai.html"},
            {"label": "Security", "href": "category-security.html"},
            {"label": "About", "href": "about.html"},
            {"label": "Contact", "href": "contact.html"},
        ],
        "footer_brand": "TechNest",
        "footer_accent_color": "brand-500",
        "hero_gradient": "from-brand-50 to-slate-200",
        "article_card_class": "",
        "button_primary": "bg-brand-600 hover:bg-brand-700",
        "link_color": "text-brand-600",
        "extra_styles": "ad-style",
    },
    "sub-travel": {
        "domain": "travel.jycsd.com",
        "base_url": "https://travel.jycsd.com",
        "brand_name": "TripRoute",
        "brand_slogan": "Explore More, Spend Less",
        "brand_desc": "Budget travel tips, destination guides, packing hacks, and digital nomad lifestyle advice.",
        "brand_logo_text": "Trip",
        "brand_logo_accent": "Route",
        "build_name": "TripRoute",
        "colors": {
            "brand": {50: '#ecfeff', 100: '#cffafe', 200: '#a5f3fc', 400: '#22d3ee', 500: '#06b6d4', 600: '#0891b2', 700: '#0e7490', 800: '#155e75'},
        },
        "font_sans": ['Roboto', 'Arial', 'Helvetica', 'sans-serif'],
        "accent_text": "text-brand-500",
        "accent_hover": "hover:text-brand-600",
        "body_class": "bg-white text-gray-800 font-sans",
        "nav_bg": "bg-white/95 backdrop-blur border-b border-gray-100 sticky top-0 z-50",
        "nav_items": [
            {"label": "Home", "href": "index.html"},
            {"label": "Budget Travel", "href": "category-budget-travel.html"},
            {"label": "Destinations", "href": "category-destinations.html"},
            {"label": "Tips", "href": "category-tips.html"},
            {"label": "Digital Nomad", "href": "category-digital-nomad.html"},
            {"label": "About", "href": "about.html"},
            {"label": "Contact", "href": "contact.html"},
        ],
        "footer_brand": "TripRoute",
        "footer_accent_color": "brand-400",
        "hero_gradient": "from-brand-600 via-brand-500 to-brand-400",
        "article_card_class": "",
        "button_primary": "bg-brand-500 hover:bg-brand-600",
        "link_color": "text-brand-600",
        "extra_styles": "ad-style",
    },
}

GA_ID = "G-GGNWR1X1GV"
ADSENSE_CLIENT = "ca-pub-2595917642864488"
CONTACT_EMAIL = "contact@jycsd.com"
FORM_SUBMIT_URL = "https://formsubmit.co/contact@jycsd.com"
